# Generated by Django 4.1.6 on 2023-10-11 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanlog',
            name='scanned_by',
        ),
        migrations.RemoveField(
            model_name='scanlog',
            name='scanned_to',
        ),
        migrations.AddField(
            model_name='scanlog',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_log_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_log_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default=uuid.UUID('a89e53ba-b524-4a7b-a403-2a5269c247dd'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learningstation',
            name='id',
            field=models.CharField(default=uuid.UUID('fd46b6a5-7326-4b4b-95f6-e352bd2209a3'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='id',
            field=models.CharField(default=uuid.UUID('5bdaefb4-0568-451f-88a3-099d15d3cae7'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='id',
            field=models.CharField(default=uuid.UUID('14978f44-10fb-4472-a50d-d124cc96a454'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.CharField(default=uuid.UUID('dcfba706-1dc3-43a6-9f6b-b1875229ea14'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasurelog',
            name='id',
            field=models.CharField(default=uuid.UUID('7cd290d7-1337-41e2-8f82-1a8c03a47115'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasures',
            name='id',
            field=models.CharField(default=uuid.UUID('523fcf06-c264-433c-80ca-672a11445098'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('40f5c092-2b66-4459-9b03-90cfba81eb93'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.CharField(default=uuid.UUID('b72221b0-2be3-402e-bbea-8afedd1b5a96'), max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='userstalllink',
            name='id',
            field=models.CharField(default=uuid.UUID('cce2eeeb-caa8-4dea-b820-f526ab2c3bdf'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
