# Generated by Django 4.1.6 on 2023-10-11 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_scanlog_scanned_by_remove_scanlog_scanned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default=uuid.UUID('9f6cad65-b003-4f77-a652-2b5469b6c54f'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learningstation',
            name='id',
            field=models.CharField(default=uuid.UUID('d72ff212-0283-416c-b059-767cb96523f6'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='id',
            field=models.CharField(default=uuid.UUID('306cd990-b1d3-4a7a-87af-c769b5c6e870'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='id',
            field=models.CharField(default=uuid.UUID('57c3af45-3cc2-43d4-a573-0123daba1577'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.CharField(default=uuid.UUID('050cfdd6-c0a3-447c-ba8f-29cbcdda5ae4'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasurelog',
            name='id',
            field=models.CharField(default=uuid.UUID('e2ff4093-9c8f-4e86-b511-9af87cc8b1b8'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasures',
            name='id',
            field=models.CharField(default=uuid.UUID('3c80c842-d4aa-4011-8938-f380f8f8651e'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('fc07bc54-4967-4801-9b5c-ba3b508b2241'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.CharField(default=uuid.UUID('318c47c9-6191-4b5d-a9fb-8b8cb0873cad'), max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='userstalllink',
            name='id',
            field=models.CharField(default=uuid.UUID('e31cd879-a833-41eb-a09d-0fd4c56fbb8a'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
