# Generated by Django 4.1.6 on 2023-10-11 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_group_id_alter_learningstation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_permenent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default=uuid.UUID('9d5499c0-db2d-4120-91fc-53465c79126b'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learningstation',
            name='id',
            field=models.CharField(default=uuid.UUID('8c066dc8-a6a3-47e1-b194-deedd6985edc'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='id',
            field=models.CharField(default=uuid.UUID('6d4c9585-76a6-4dee-983f-dd9231f4ce19'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='id',
            field=models.CharField(default=uuid.UUID('20837cf6-1845-49a8-be51-f786478425f5'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.CharField(default=uuid.UUID('7d1a1057-bc90-4bf0-bf7e-304e2be05065'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasurelog',
            name='id',
            field=models.CharField(default=uuid.UUID('06074824-5f16-483d-91d7-1625dfec6c89'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasures',
            name='id',
            field=models.CharField(default=uuid.UUID('9c9f0308-59fc-43a2-a709-8714072fa279'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('0a6ddda3-b6aa-4f30-b949-c77ce0119753'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.CharField(default=uuid.UUID('9299e496-f0bb-4de4-8f2f-5b94bf491c10'), max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='userstalllink',
            name='id',
            field=models.CharField(default=uuid.UUID('f08b1e85-5422-440c-ae24-d3c2a3f2168b'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
