# Generated by Django 4.1.6 on 2023-10-12 08:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_user_is_permenent_alter_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default=uuid.UUID('f4000bcb-25a4-4e75-855b-7eb577ea91c4'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learningstation',
            name='id',
            field=models.CharField(default=uuid.UUID('226a690b-780d-4e4c-ae47-dbdbc6e23361'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='id',
            field=models.CharField(default=uuid.UUID('d5db0ded-8be2-44ba-9fb4-9cf857a9dd08'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='id',
            field=models.CharField(default=uuid.UUID('43ff97b6-ba49-4d6f-a17a-2f38c2ba3bbb'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.CharField(default=uuid.UUID('95047b44-f2fa-4729-ba1f-35ff215fd7fb'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasurelog',
            name='id',
            field=models.CharField(default=uuid.UUID('84319fde-8478-48aa-8b77-018e68adc616'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasures',
            name='id',
            field=models.CharField(default=uuid.UUID('384ef1f4-00d9-41a8-b6d0-965d327ab028'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('a19b5d45-808a-46cd-9ee1-7aeb08ba4040'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.CharField(default=uuid.UUID('4784e94f-e970-4de7-be4b-599391e7bc79'), max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='userstalllink',
            name='id',
            field=models.CharField(default=uuid.UUID('f027733c-282e-450d-9d47-56ccafc750cb'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
