# Generated by Django 4.1.6 on 2023-10-12 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_user_password_alter_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default=uuid.UUID('fc931987-4443-452e-8b7c-7d654495a388'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learningstation',
            name='id',
            field=models.CharField(default=uuid.UUID('08e4593d-9893-481b-b79e-62de5a5eed36'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='id',
            field=models.CharField(default=uuid.UUID('e27ea37e-d71a-4f67-ba56-da8a6720ca7d'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='id',
            field=models.CharField(default=uuid.UUID('7bd98359-13f5-4c74-ab15-6f7a649efe7b'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.CharField(default=uuid.UUID('26953c06-d38c-4512-ae12-19b72f318678'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasurelog',
            name='id',
            field=models.CharField(default=uuid.UUID('9182f645-0836-4440-a58d-ba9d721bf6a3'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treasures',
            name='id',
            field=models.CharField(default=uuid.UUID('a59fd0f5-568f-48a5-a15d-d87786ac814d'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('5a5c82b2-ff97-496e-bd0d-05f9510f865d'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.CharField(default=uuid.UUID('5fc2c067-b13f-460d-918a-8862a1b783fb'), max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='userstalllink',
            name='id',
            field=models.CharField(default=uuid.UUID('44cc2c7a-4ce6-45e1-bab2-e40636d7553f'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
